$(document).ready(function(){
  $('.menuIcon').click(function(){
    if($('.wrap').hasClass('menu-active')){
      $('.wrap').removeClass('menu-active');
    }
    else{
      $('.wrap').addClass('menu-active');
    }
  })
})